### ISSUE TITLE
/phaseの設定が終わった後、設定した色をグラフの方に反映させる

### ISSUE THREAD

**Issue by KinoshitaMisaki** [Protein-research-group/AKTA-DB#5]
/phaseでPOSTした内容がcsvに反映された後、その色コードを使用してグラフのphase colorを変更する。多分、次のpooling処理のhtmlを読む段階で同時実行することかと思われます。

**Comment by Tsuchihashi-ryo** [comment]
グラフは毎回、csvを読み取って作成されるので、おそらくページジャンプしたときに再構成されます。
